apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mcp-demo
resources:
  - app.yaml
configMapGenerator:
  - name: mcp-demo-code
    files:
      - server.py
      - mcp-manifest.json
generatorOptions:
  labels:
    app.kubernetes.io/name: mcp-demo
